#!/usr/bin/env python3
# Copyright 2026 Dhruv Menon
# SPDX-License-Identifier: Apache-2.0
"""Amalgamate PolyOnTest Core into dist/polyontest.h + dist/polyontest.c."""

from __future__ import annotations

import argparse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INCLUDE_DIR = ROOT / "harness" / "include" / "polyontest"
HEADER_SRC = INCLUDE_DIR / "polyontest.h"
PROFILE_SRC = INCLUDE_DIR / "polyontest_profile.h"
CORE_DIR = ROOT / "harness" / "c"
OUT_DIR = ROOT / "dist"


def inline_profile(header: str, profile: str) -> str:
    """Replace #include \"polyontest/polyontest_profile.h\" with inlined profile body."""
    # Strip include guard from profile so we don't nest awkwardly; keep contents.
    body = profile
    body = re.sub(r"#ifndef POLYONTEST_PROFILE_H\n", "", body, count=1)
    body = re.sub(r"#define POLYONTEST_PROFILE_H\n", "", body, count=1)
    body = re.sub(r"#endif /\* POLYONTEST_PROFILE_H \*/\n?\Z", "", body)
    pattern = r'#include\s+"polyontest/polyontest_profile\.h"\s*\n'
    replacement = (
        "/* ---- inlined polyontest_profile.h ---- */\n"
        + body
        + "/* ---- end polyontest_profile.h ---- */\n"
    )
    out, n = re.subn(pattern, replacement, header, count=1)
    if n != 1:
        raise SystemExit("Failed to inline polyontest_profile.h into polyontest.h")
    return out


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("-o", "--out", type=Path, default=OUT_DIR)
    args = parser.parse_args()
    args.out.mkdir(parents=True, exist_ok=True)

    header = HEADER_SRC.read_text(encoding="utf-8")
    profile = PROFILE_SRC.read_text(encoding="utf-8")
    header = inline_profile(header, profile)

    sources = sorted(CORE_DIR.glob("*.c"))
    if not sources:
        raise SystemExit(f"No C sources under {CORE_DIR}")

    parts: list[str] = []
    for src in sources:
        text = src.read_text(encoding="utf-8")
        text = text.replace('#include "polyontest/polyontest.h"', '#include "polyontest.h"')
        parts.append(f"\n/* ---- {src.name} ---- */\n")
        parts.append(text)
    core = "".join(parts)

    banner_h = (
        "/* Amalgamated PolyOnTest Core header — DO NOT EDIT.\n"
        " * Generated by scripts/amalgamate.py\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " */\n"
    )
    banner_c = (
        "/* Amalgamated PolyOnTest Core source — DO NOT EDIT.\n"
        " * Generated by scripts/amalgamate.py\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " *\n"
        " * Drop polyontest.h + polyontest.c into your project and compile polyontest.c.\n"
        " */\n"
    )

    (args.out / "polyontest.h").write_text(banner_h + header, encoding="utf-8")
    (args.out / "polyontest.c").write_text(banner_c + core, encoding="utf-8")
    # Also copy modular profile for dual-layout consumers.
    (args.out / "polyontest_profile.h").write_text(
        "/* Copied from harness — also inlined into polyontest.h. */\n" + profile,
        encoding="utf-8",
    )
    # Remove legacy amalgam filenames if present.
    for legacy in ("polytest.h", "polytest.c", "polytest_profile.h"):
        p = args.out / legacy
        if p.exists():
            p.unlink()
    print(f"Wrote {args.out / 'polyontest.h'} (profile inlined)")
    print(f"Wrote {args.out / 'polyontest.c'} ({len(sources)} translation units)")
    print(f"Wrote {args.out / 'polyontest_profile.h'}")


if __name__ == "__main__":
    main()
